version: '4'

services:
  # Servicio para la aplicación Laravel
  app:
    image: php8:laravel1
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  # Servicio para la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  # Servicio para el servidor web Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel

# Definición de volúmenes
volumes:
  dbdata:

# Definición de redes
networks:
  laravel:
